# Generated by Django 4.2 on 2023-07-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(default=5355091046, max_length=20),
            preserve_default=False,
        ),
    ]
