# Generated by Django 4.2 on 2023-06-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
