# Generated by Django 4.2 on 2023-06-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0002_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='default',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
