# Generated by Django 4.2 on 2023-06-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0005_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_image',
            field=models.ImageField(default=1, upload_to='ProductsImages'),
            preserve_default=False,
        ),
    ]
