# Generated by Django 4.2 on 2023-06-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0006_product_default_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='default',
        ),
    ]
