# Generated by Django 4.2 on 2023-06-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0009_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
