# Generated by Django 4.2 on 2023-07-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0011_shipping_shippingproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
