# Generated by Django 4.0.6 on 2023-07-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0012_alter_shipping_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingproducts',
            name='shipping',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
        migrations.DeleteModel(
            name='ShippingProducts',
        ),
    ]
