# Generated by Django 4.2 on 2023-07-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
